package com.example.catalist.repository

import com.example.catalist.model.CatData

val SampleData = listOf(
    CatData(
        id = "1",
        name = "Abyssinian",
        alternativeName = "Aby",
        description = "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
        origin = "Ethiopia, Somalia, Srbistan, Ethiopia, Somalia, Srbistan",
        temperament = "Active, Energetic, Independent, Intelligent, Gentle",
        lifeSpan = "12 - 15",
        weight = "8 - 12",
        adaptability = 5,
        affectionLevel = 2,
        childFriendly = 3,
        dogFriendly = 4,
        energyLevel = 1,
        rare = 0,
        link = "https://www.petfinder.com/cat-breeds/abyssinian/",
    ),
    CatData(
        id = "2",
        name = "American Bobtail",
        alternativeName = "Bobtail",
        description = "American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance.",
        origin = "United States, North America",
        temperament = "Intelligent, Interactive, Lively, Playful, Sensitive",
        lifeSpan = "11 - 15",
        weight = "7 - 16",
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 4,
        dogFriendly = 5,
        energyLevel = 5,
        rare = 0,
        link = "https://www.petfinder.com/cat-breeds/american-bobtail/",
    ),
    CatData(
        id = "3",
        name = "American Curl",
        alternativeName = null,
        description = "The American Curl is best known for its unique ears that curl backward, creating a cute and unusual look.",
        origin = "United States, Serbia, Spain",
        temperament = "Affectionate, Curious, Intelligent, Interactive, Lively",
        lifeSpan = "12 - 16",
        weight = "5 - 10",
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 4,
        dogFriendly = 5,
        energyLevel = 3,
        rare = 0,
        link = "https://www.petfinder.com/cat-breeds/american-curl/",
    ),
    CatData(
        id = "4",
        name = "American Shorthair",
        alternativeName = "Domestic Shorthair",
        description = "The American Shorthair is a breed of domestic cat believed to be descended from European cats brought to North America by early settlers to protect valuable cargo from mice and rats.sdadsadsdasdsadahjsgd jasgd jgashjdg ahjsgd hgasg djhagshjdgajhs gdhags jdgajsgd jagdjags sdgaj gdasjg djags djagshj dgjahgd ashdg jagsd jasgd ja",
        origin = "United States",
        temperament = "Active, Curious, Easy Going, Playful, Calm",
        lifeSpan = "15 - 17",
        weight = "8 - 15",
        adaptability = 5,
        affectionLevel = 5,
        childFriendly = 5,
        dogFriendly = 5,
        energyLevel = 3,
        rare = 0,
        link = "https://www.petfinder.com/cat-breeds/american-shorthair/",
    ),

)